-- 006_embedding_provenance.sql
--
--   image_embeddings + source_text, provider, normalized, updated_at
--
-- Phase 2. Written after the first embedding job ran, which exposed what the
-- Phase 1 table could not record.

-- ---------------------------------------------------------------------------
-- WHY THESE COLUMNS
-- ---------------------------------------------------------------------------
--
-- `source_text` — the most important of the four.
--
--   An embedding without the text it came from is not auditable. If a caption is
--   later regenerated by a different model, or the caption itself is corrected,
--   there is no way to tell which caption produced a stored vector. Phase 3
--   compares post embeddings against these vectors, and Phase 4 reports the
--   precision that follows; a precision figure that cannot be traced to the text
--   behind its vectors cannot be reproduced or defended.
--
--   This is the embedding-side equivalent of storing raw_response on
--   image_metadata.
--
-- `provider` — gemini and ollama can both produce vectors for the same caption.
--   Recording which one keeps attribution honest when a corpus run mixes them,
--   and matches how ai_calls already attributes every call.
--
-- `normalized` — the project L2-normalises embeddings before persisting them
--   because Gemini's 768-dimension output is NOT pre-normalised while its
--   3072-dimension default is (measured: L2 0.587787 vs 1.000000; see
--   docs/adr/002-embedding-dimension.md).
--
--   Storing the flag rather than assuming it means a future consumer can tell a
--   normalised vector from one that merely happened to arrive that way, instead
--   of trusting an invariant that lives only in a comment.
--
-- `updated_at` — required so a retried embedding job can converge on one row via
--   ON CONFLICT DO UPDATE without every retry erroring on a missing column.
ALTER TABLE image_embeddings
  ADD COLUMN source_text TEXT,
  ADD COLUMN provider TEXT,
  ADD COLUMN normalized BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- `dimensions` is NOT NULL with no default, which forces the caller to state the
-- width rather than letting pgvector infer it. Give it a CHECK tying it to the
-- column type so a mismatch is rejected at the table rather than discovered when
-- a cosine comparison silently returns nonsense.
ALTER TABLE image_embeddings
  ADD CONSTRAINT image_embeddings_dimensions_match
  CHECK (dimensions = 768);

-- Phase 3 builds its candidate set by looking up an embedding for a specific
-- image and model, so this lookup is on the hot path.
CREATE INDEX idx_image_embeddings_model ON image_embeddings (model, model_version);

CREATE TRIGGER image_embeddings_set_updated_at
  BEFORE UPDATE ON image_embeddings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON COLUMN image_embeddings.source_text IS
  'The exact text that was embedded. Makes a stored vector reproducible and '
  'lets a later caption revision be detected rather than silently reused.';

COMMENT ON COLUMN image_embeddings.normalized IS
  'True when the vector was L2-normalised before insertion. Gemini only '
  'pre-normalises its default 3072-dimension output, not truncated 768-dimension '
  'output, so the project normalises explicitly.';